package io.todo.task.exceptions;

public class TaskNotFoundException extends Exception{
}
